blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='blogindex'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

eoghansite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
from django.urls import path

from . import views

app_name = 'personal'
urlpatterns = [
    path('', views.index, name='index'),
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=50)
    summary = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    header = models.ImageField(upload_to='headers/%Y/%m/%d/')

    def __str__(self):
        return self.title

class Paragraph(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(blank=True, default="default_content")
    main_image = models.ImageField(upload_to='post_images', blank=True)
    caption = models.CharField(max_length=300, blank=True)

personal/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views import generic

from .models import Post

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        """Return published blog Posts."""
        return Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DetailView, self).get_context_data(*args, **kwargs)
        context['post_list'] = Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
        return context

personal/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'personal/index.html')

blog/templates/blog/detail.html
{% extends "personal/base.html" %}
{% block content %}
{% load static %}
  <div class = "container" id="blog">
    <div class="row">
      <div class="col-md-auto">
        {% include "blog/includes/recentposts.html" %}
      </div>
      <div class = "col-md mt-3">
        <img class="img-fluid img-thumbnail" src="{{post.header.url}}">
        <h2 class="mt-2" style="color:#0074D9;">{{post.title}}</h2>
        <h5 style="color:#0074D9;">{{post.summary}}</h5>
        {% for paragraph in post.paragraph_set.all %}
          <p>{{paragraph.content}}</p>
            {% if paragraph.main_image and paragraph.caption %}
              <center>
              <figure class="figure">
                <img src="{{ paragraph.main_image.url }}" class="figure-img img-fluid img-thumbnail" alt="{{paragraph.caption}}">
                <figcaption class="figure-caption text-center">{{paragraph.caption}}</figcaption>
              </figure>
              </center>
            {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/includes/recentposts.html
{% block content %}
  <div class="card mt-3" style="width: 18rem;">
    <div class="card-header">
      <h3> Recent Blogs </h3>
    </div>
  {% if post_list %}
    <ul class="list-group list-group-flush">
      {% for post in post_list|slice:":5" %}
        <a href="{% url 'blog:detail' post.id %}" class="list-group-item list-group-item-action">
          {{post.title}}<br><small>{{post.pub_date}}</small>
        </a>
      {% endfor %}
    </ul>
  {% else %}
    <p>No blogs available</p>
  {% endif %}
  </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "personal/base.html" %}
{% block content %}
{% load static %}
<div class="container" id="blog">
    <div class="row">
      <div class="col-md-auto">
        {% include "blog/includes/recentposts.html" %}
      </div>
      <div class="col-md mt-3">
      {% if post_list %}

        {% for post in post_list %}
            <div class="card mb-3">
              <img class="card-img-top" src="{{post.header.url}}" alt="Card image cap">
              <div class="card-body">
                <h3 class="card-title">{{post.title}}</h3>
                <p class="card-text">{{post.summary}}</p>
                <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Read More...</a>
              </div>
            </div>

        {% endfor %}
      {% else %}
        <p>No blogs available</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}


<div class="card mb-3">
  <img class="card-img-top" src=".../100px180/" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>

personal/templates/personal/base.html
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125492483-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-125492483-1');
    </script>

    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'personal/style/style.css' %}">

    <title>Eoghan Murphy</title>
  </head>


<body data-spy="scroll" data-target="#site-navbar" data-offset="300" style="background-color: #f7f7f7">

  <nav id="site-navbar" class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #0074D9">
    <a class="navbar-brand" href="{% url 'personal:index' %}">
      <img src="{% static 'personal/img/elogonav.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      Eoghan Murphy
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" data-target="#home" href="{% url 'personal:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-target="#blog" href="{% url 'blog:blogindex' %}">Blog</a>
        </li>
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <footer class="mt-5" style="background-color: #0074D9">
    <div class="container pt-3">
      <div class="row">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-3 offset-sm-3" style="color:white">
          <h4>SOCIAL</h4>
          <ul class="list-unstyled footer-social">
          <li><a href="https://www.linkedin.com/in/eoghan-murphy-45034515a"><i class="fab fa-linkedin-in"></i> LinkedIn</a></li>
          <li><a href="https://twitter.com/Eoghan_Murphy1"><i class="fab fa-twitter"></i> Twitter</a></li>
          <li><a href="https://github.com/Eoghan-Murphy"><i class="fab fa-github"></i> GitHub</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

</html>

personal/templates/personal/index.html
{% extends "personal/base.html" %}

{% block content %}
{% load static %}
<div id="home">
  <div id="about" class="container" style="margin-top:56px;">
    <div class ="row justify-content-center">

      <div class = "col-sm-4 align-self-center">
        <center>
          <img src="{% static 'personal/img/elogo.svg' %}" class="img-fluid" alt="Logo" style="max-width: 60%">
        </center>
      </div>
      <div class = "col-sm-6 align-self-center">
        <center>
          <h1 style= "color: #0074D9"> Eoghan Murphy</h1>
          <h3>A Third Year Computer Applications Student at Dublin City University with an Interest in Software Development.</h3>
        </center>
      </div>
    </div>
  </div>


  <div id="projects" class="container" style="padding-top:56px;">
    <center>
    <h2>Projects</h2>
  </center>
    <div class ="row">
      <div class = "col-sm pb-3">
        <center>
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{% static 'personal/img/tightrope.png' %}" alt="Screenshot of game 'TightRope!'">
          <div class="card-body">
            <h5 class="card-title">TightRope!</h5>
            <p class="card-text">An arcade game about balancing on a rope, released on the Google Play Store.</p>
            <p><small>Skills: C#, Unity, Illustrator, Blender</small><p>
            <a href="https://play.google.com/store/apps/details?id=com.ghostmuttgames.tightrope" class="btn btn-primary">Check It Out</a>
          </div>
        </div>
        </center>
      </div>
            <div class = "col-sm pb-3">
        <center>
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{% static 'personal/img/blogproject.png' %}" alt="The word blog surrounded by angle brackets.">
          <div class="card-body">
            <h5 class="card-title">Blog</h5>
            <p class="card-text">A personal blog, available on this website.</p>
            <p><small>Skills: Python, Django, Web Development, Apache</small><p>
            <a href="{% url 'blog:blogindex' %}" class="btn btn-primary">Check It Out</a>
          </div>
        </div>
        </center>
      </div>

      <div class = "col-sm pb-3">
        <center>
          <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'personal/img/gamereviewlogo.svg' %}" alt="A blue game controller.">
          <div class="card-body">
            <h5 class="card-title">Loading Review</h5>
            <p class="card-text">A game review site developed with Django.</p>
            <p><small>Skills: Python, Django, Web Development, Apache</small><p>
            <a href="www.loadingreview.com" class="btn btn-primary">Check It Out</a>
          </div>
         </div>
      </center>
     </div>
      </div>
    </div>


  <div class="container pt-5" id="grades" style="padding-top:56px;">
    <h2>Grades</h2>

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link" id="pills-year1-tab" data-toggle="pill" href="#pills-year1" role="tab" aria-controls="pills-year1" aria-selected="false">Year 1</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" id="pills-year2-tab" data-toggle="pill" href="#pills-year2" role="tab" aria-controls="pills-year2" aria-selected="true">Year 2</a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade" id="pills-year1" role="tabpanel" aria-labelledby="pills-year1-tab">
        <table class="table table-hover table-dark">
          <thead>
            <tr>
              <th scope="col">Subject</th>
              <th scope="col">Grade</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Computer Systems</td>
              <td>99%</td>
            </tr>
            <tr>
              <td>Web Design</td>
              <td>81%</td>
            </tr>
            <tr>
              <td>Programming I</td>
              <td>98%</td>
            </tr>
            <tr>
              <td>Problem-Solving <small> (Not attended due to sickness.) </small></td>
              <td>38%</td>
            </tr>
            <tr>
              <td>Digital Innovation</td>
              <td>72%</td>
            </tr>
            <tr>
              <td>Programming II</td>
              <td>95%</td>
            </tr>
            <tr>
              <td>Networks and Internet</td>
              <td>78%</td>
            </tr>
            <tr>
              <td>Intro. to Operating Systems</td>
              <td>97%</td>
            </tr>
            <tr>
              <td>IT Mathematics</td>
              <td>92%</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="tab-pane fade show active" id="pills-year2" role="tabpanel" aria-labelledby="pills-year2-tab">
        <table class="table table-hover table-dark">
          <thead>
            <tr>
              <th scope="col">Subject</th>
              <th scope="col">Grade</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Logic</td>
              <td>89%</td>
            </tr>
            <tr>
              <td>Systems Analysis</td>
              <td>78%</td>
            </tr>
            <tr>
              <td>Introduction to Databases</td>
              <td>72%</td>
            </tr>
            <tr>
              <td>Computer Programming III</td>
              <td>94%</td>
            </tr>
            <tr>
              <td>Compt. Archit. & Assembly Level Programming</td>
              <td>93%</td>
            </tr>
            <tr>
              <td>Operating Systems</td>
              <td>88%</td>
            </tr>
            <tr>
              <td>Advanced Computer Architectures</td>
              <td>95%</td>
            </tr>
            <tr>
              <td>Probability & Statistics</td>
              <td>82%</td>
            </tr>
            <tr>
              <td>Software Testing</td>
              <td>84%</td>
            </tr>
            <tr>
              <td>Computer Programming IV</td>
              <td>90%</td>
            </tr>
            <tr>
              <td>Linear Algebra</td>
              <td>88%</td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>
{% endblock %}